### ISSUE TITLE
Update to Deb12 Bookworm Mono Image

### ISSUE THREAD

**Issue by sveken** [shadowpanther/resonite-headless#7]
Hello, 
It looks like the mono image this is based on as not been touched in about 2 years, and it starting to show its age with issues such as https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1241 due to old version of glibc.

Would it be possible to get the image updated to something like Debian 12? 

Thank you,

**Comment by sveken** [comment]
It appears this has already been done here. https://github.com/ijs01140/resonite-headless 
I think it would just require syncing/merging the fork? 

EDIT. Just tried the above image and it still has the freeimage error with the libc version

**Comment by shadowpanther** [comment]
@sveken it looks like just the base `mono` image was replaces, but it's a private image, not an official one, so I don't want to risk switching to it. Mono version is the same in it.

You can probably just use their image https://hub.docker.com/r/ijs01140/resonite-headless instead of mine if you want the newer base system.
